/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Basics',
      collapsed: false,
      items: [
        'tutorial-basics/congratulations',
        'tutorial-basics/create-a-page',
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/deploy-your-site',
      ],
    },
    {
      type: 'category',
      label: 'Extras',
      collapsed: true,
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
  ],

  ireSidebar: [
    'ikyr-render-engine',
    {
      type: 'category',
      label: 'First steps',
      collapsed: false,
      items: [
        'ire/installation',
        'ire/hello_world',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'ire/explain_hello_world',
      ],
    },
    {
      type: 'category',
      label: 'Documentation',
      collapsed: false,
      items: [
        'ire/doc/context',
        'ire/doc/z-order',
      ],
    },
  ],
  
  igeSidebar: [
    'ikyr-game-engine'
  ],
};
